# vim: set expandtab shiftwidth=2 softtabstop=2 :

language: cpp
sudo: required
service:
- docker

env:
  global:
  - MY_NAME=travis-ci
  - MY_TARGET_MOUNT=/tell/ntl-unix
matrix:
  include:
  - os: linux
    dist: xenial
    compiler: gcc
    env:
    - MY_TARGET_DIST=ubuntu:18.04
  - os: osx
    osx_image: xcode10.1
    compiler: clang
    env:
    - MY_CXX=clang++

before_install:
- if [[ ! -z "$MY_CXX" ]]; then export CXX=$MY_CXX; fi
- ./travis-ci/before_install_$TRAVIS_OS_NAME.bash
install:
- ./travis-ci/install_$TRAVIS_OS_NAME.bash

before_script:
- echo $CC; $CC --version
- echo $CXX; $CXX --version
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker exec -ti $MY_NAME bash -c "echo $CC; $CC --version"; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker exec -ti $MY_NAME bash -c "echo $CXX; $CXX --version"; fi

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker exec -ti $MY_NAME bash -c "cd $MY_TARGET_MOUNT; make" | cat -n | awk '{ print $1 }' | sed -n -e 's/[05]00$/*/p'; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker exec -ti $MY_NAME bash -c "cd $MY_TARGET_MOUNT; make check"; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make | cat -n | awk '{ print $1 }' | sed -n -e 's/[05]00$/*/p'; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make check; fi

# after_failure:
# - tail -n 1000 make.log

notifications:
  on_success: change
  on_failure: always
