# vim: set expandtab shiftwidth=2 softtabstop=2 :

language: cpp
sudo: required
service:
- docker

env:
  global:
  - MY_NAME=travis-ci
  - MY_TARGET_MOUNT=/tell/ntl-unix
matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
    env:
    - MY_TARGET_DIST=ubuntu:18.04

before_install:
- docker pull $MY_TARGET_DIST
- docker run --name $MY_NAME -v $TRAVIS_BUILD_DIR:$MY_TARGET_MOUNT -td $MY_TARGET_DIST /bin/bash

install:
- docker exec -ti $MY_NAME bash -c "apt update" > /dev/null
- docker exec -ti $MY_NAME bash -c "apt install -y build-essential" > /dev/null
- docker exec -ti $MY_NAME bash -c "apt install -y libgmp-dev" > /dev/null

before_script:
- docker exec -ti $MY_NAME bash -c "$CC --version"
- docker exec -ti $MY_NAME bash -c "$CXX --version"

script:
- docker exec -ti $MY_NAME bash -c "cd $MY_TARGET_MOUNT ; make" | cat -n | awk '{ print $1 }' | sed -n -e 's/[05]00$/*/p' | tr -d '\n'
- docker exec -ti $MY_NAME bash -c "cd $MY_TARGET_MOUNT ; make check"

# after_failure:
# - tail -n 1000 make.log

notifications:
  on_success: change
  on_failure: always
