language: cpp
sudo: false
cache:
    apt: true
addons:
    apt:
        sources:
            # - deadsnakes
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9
        - libgmp-dev
compiler:
- g++-4.9
before_script:
- CXX=g++-4.9 make 2>&1 > make.log || { echo "!!!! ERROR !!!!"; cat make.log; false; }
script: make check
# after_failure:
#     - "pwd"
#     - "cat config.log"
