language: cpp
sudo: false
cache:
    apt: true
addons:
    apt:
        sources:
            # - deadsnakes
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
        - libgmp-dev
compiler:
- g++-4.8
before_script:
- make
script: make check
# after_failure:
#     - "pwd"
#     - "cat config.log"
