language: cpp
sudo: false

matrix:
  include:
  - os: linux
    compiler: gcc
    env: CXX_=g++-5
    addons:
      apt:
        sources:
        # - deadsnakes
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - libgmp-dev
    cache:
      apt: true
  - os: linux
    dist: xenial
    compiler: clang
    env: CXX_=clang++
    addons:
      apt:
        sources:
        - llvm-toolchain-precise-3.8
        packages:
        - libgmp-dev
    cache:
      apt: true
    sudo: required
  - os: osx
    osx_image: xcode8
    compiler: gcc
    env: CXX_=g++-5
  - os: osx
    osx_image: xcode8
    compiler: clang
    env: CXX_=clang++

before_install:
- export CXX=$CXX_

install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CXX" == "clang++" ]]; then sudo apt install clang-3.8 -y; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-sed; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$CXX" == g++* ]]; then brew install gcc5; fi

before_script:
- $CXX --version

script:
- make -j 2>&1 > make.log
- make check

after_failure:
- tail -n 1000 make.log

notifications:
  on_success: change
  on_failure: always
